export enum AuthStatus {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADED = 'USER_LOADED',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED'
}

export enum ProfileStatus {
  GET_PROFILE = 'GET_PROFILE',
  GET_PROFILES = 'GET_PROFILES',
  GET_REPOS = 'GET_REPOS',
  PROFILE_ERROR = 'PROFILE_ERROR',
  CLEAR_PROFILE = 'CLEAR_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE'
}

export enum PostStatus {
  GET_POST = 'GET_POST',
  GET_POSTS = 'GET_POSTS',
  POST_ERROR = 'POST_ERROR',
  UPDATE_LIKES = 'UPDATE_LIKES',
  DELETE_POST = 'DELETE_POST',
  ADD_POST = 'ADD_POST',
  ADD_COMMENT = 'ADD_COMMENT',
  DELETE_COMMENT = 'DELETE_COMMENT',
  CLEAR_POST = 'CLEAR_POST'
}
