export enum AlertStatus {
  SET_ALERT = 'SET_ALERT',
  REMOVE_ALERT = 'REMOVE_ALERT'
}

export enum AuthStatus {
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL',
  USER_LOADED = 'USER_LOADED',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT'
}

export enum ProfileStatus {
  GET_PROFILE = 'GET_PROFILE',
  PROFILE_ERROR = 'PROFILE_ERROR',
  CLEAR_PROFILE = 'CLEAR_PROFILE',
  UPDATE_PROFILE = 'UPDATE_PROFILE'
}
